/**
 * Soul Cosmos - 易经引擎 (I Ching Engine)
 * 64卦完整数据 + 占卜算法
 */
const IChing = {
  // 八卦基础
  TRIGRAMS: {
    '111': { name: '乾', symbol: '☰', english: 'Heaven', element: 'Metal', quality: 'Creative' },
    '000': { name: '坤', symbol: '☷', english: 'Earth', element: 'Earth', quality: 'Receptive' },
    '100': { name: '震', symbol: '☳', english: 'Thunder', element: 'Wood', quality: 'Arousing' },
    '011': { name: '巽', symbol: '☴', english: 'Wind', element: 'Wood', quality: 'Gentle' },
    '010': { name: '坎', symbol: '☵', english: 'Water', element: 'Water', quality: 'Abysmal' },
    '101': { name: '离', symbol: '☲', english: 'Fire', element: 'Fire', quality: 'Clinging' },
    '001': { name: '艮', symbol: '☶', english: 'Mountain', element: 'Earth', quality: 'Stillness' },
    '110': { name: '兑', symbol: '☱', english: 'Lake', element: 'Metal', quality: 'Joyous' },
  },

  // 64卦完整数据
  HEXAGRAMS: [
    { number: 1, name: '乾', english: 'The Creative', symbol: '䷀', upper: '111', lower: '111',
      judgment: '元亨利贞。', judgmentEn: 'Sublime success. Perseverance furthers.',
      image: '天行健，君子以自强不息。', imageEn: 'The movement of heaven is full of power. Thus the superior man makes himself strong and untiring.',
      keywords: ['Leadership', 'Initiative', 'Power', 'Heaven'],
      personality: 'You are a natural leader with unstoppable creative energy. Like heaven itself, you move with constant, powerful motion. Your strength is in initiating and inspiring.' },
    { number: 2, name: '坤', english: 'The Receptive', symbol: '䷁', upper: '000', lower: '000',
      judgment: '元亨，利牝马之贞。', judgmentEn: 'The mare sublime success. Perseverance furthers.',
      image: '地势坤，君子以厚德载物。', imageEn: 'The earth\'s condition is receptive devotion. Thus the superior man carries things with broad virtue.',
      keywords: ['Receptivity', 'Nurturing', 'Support', 'Earth'],
      personality: 'You possess the infinite nurturing power of earth. Your strength is not in leading but in supporting, sustaining, and creating the foundation for others to thrive.' },
    { number: 3, name: '屯', english: 'Difficulty at the Beginning', symbol: '䷂', upper: '010', lower: '100',
      judgment: '元亨，利贞。勿用有攸往，利建侯。', judgmentEn: 'Success. Perseverance furthers. Do not put to use. It furthers to appoint helpers.',
      image: '云雷屯，君子以经纶。', imageEn: 'Clouds and thunder: the image of Difficulty at the Beginning. Thus the superior man brings order out of confusion.',
      keywords: ['New Beginnings', 'Chaos', 'Potential', 'Growth'],
      personality: 'You thrive in chaos and new beginnings. Where others see confusion, you see raw potential. Your gift is bringing order from disorder.' },
    { number: 4, name: '蒙', english: 'Youthful Folly', symbol: '䷃', upper: '001', lower: '010',
      judgment: '亨。匪我求童蒙，童蒙求我。', judgmentEn: 'Success. It is not I who seek the young fool; the young fool seeks me.',
      image: '山下出泉，蒙。君子以果行育德。', imageEn: 'A spring wells up at the foot of the mountain: the image of Youth. Thus the superior man fosters his character by thoroughness of action.',
      keywords: ['Learning', 'Humility', 'Teaching', 'Growth'],
      personality: 'You are a lifelong learner with the humility to admit what you don\'t know. Your wisdom grows through seeking knowledge and being open to guidance.' },
    { number: 5, name: '需', english: 'Waiting', symbol: '䷄', upper: '010', lower: '111',
      judgment: '有孚，光亨，贞吉。利涉大川。', judgmentEn: 'If you are sincere, you have light and success. Perseverance brings good fortune.',
      image: '云上于天，需。君子以饮食宴乐。', imageEn: 'Clouds rise up to heaven: the image of Waiting. Thus the superior man eats and drinks, is joyous and of good cheer.',
      keywords: ['Patience', 'Trust', 'Timing', 'Nourishment'],
      personality: 'You understand the power of patient waiting. Like clouds gathering before rain, you know that the right moment always comes to those who prepare with trust.' },
    { number: 6, name: '讼', english: 'Conflict', symbol: '䷅', upper: '111', lower: '010',
      judgment: '有孚窒惕，中吉，终凶。利见大人。', judgmentEn: 'You are sincere and are obstructed. Caution brings good fortune in the middle. In the end misfortune.',
      image: '天与水违行，讼。君子以作事谋始。', imageEn: 'Heaven and water go opposite ways: the image of Conflict. Thus the superior man reflects on things before undertaking them.',
      keywords: ['Conflict', 'Resolution', 'Wisdom', 'Prevention'],
      personality: 'You understand that conflict is sometimes inevitable, but true wisdom lies in preventing it before it begins. Your strength is in strategic thinking.' },
    { number: 7, name: '师', english: 'The Army', symbol: '䷆', upper: '000', lower: '010',
      judgment: '贞丈人吉，无咎。', judgmentEn: 'The army needs perseverance and a strong man. Good fortune without blame.',
      image: '地中有水，师。君子以容民畜众。', imageEn: 'In the earth there is water: the image of The Army. Thus the superior man increases his masses by generosity toward the people.',
      keywords: ['Discipline', 'Leadership', 'Organization', 'Strategy'],
      personality: 'You lead through discipline and strategic organization. Like a wise general, you know that true power comes from the unity and loyalty of your people.' },
    { number: 8, name: '比', english: 'Holding Together', symbol: '䷇', upper: '010', lower: '000',
      judgment: '吉。原筮元永贞，无咎。', judgmentEn: 'Good fortune. Seek unity with perseverance and no blame.',
      image: '地上有水，比。先王以建万国，亲诸侯。', imageEn: 'On the earth is water: the image of Holding Together. Thus the kings of old established states and fostered relations with vassals.',
      keywords: ['Unity', 'Cooperation', 'Loyalty', 'Community'],
      personality: 'You are a natural connector who brings people together. Your gift is creating bonds of loyalty and mutual support that stand the test of time.' },
    { number: 9, name: '小畜', english: 'The Taming Power of the Small', symbol: '䷈', upper: '110', lower: '111',
      judgment: '亨。密云不雨，自我西郊。', judgmentEn: 'Success. Dense clouds, no rain from our western territories.',
      image: '风行天上，小畜。君子以懿文德。', imageEn: 'The wind blows high in the sky: the image of Small Taming. Thus the superior man refines the outward aspect of his nature.',
      keywords: ['Patience', 'Subtlety', 'Refinement', 'Restraint'],
      personality: 'You understand that small, consistent efforts create great change over time. Your power lies in gentle persistence and refined influence.' },
    { number: 10, name: '履', english: 'Treading', symbol: '䷉', upper: '111', lower: '110',
      judgment: '履虎尾，不咥人，亨。', judgmentEn: 'Treading upon the tail of the tiger. It does not bite the man. Success.',
      image: '上天下泽，履。君子以辩上下，定民志。', imageEn: 'Heaven above, the lake below: the image of Treading. Thus the superior man discriminates between high and low.',
      keywords: ['Courage', 'Conduct', 'Respect', 'Grace'],
      personality: 'You walk through danger with grace and proper conduct. Your courage is not reckless but measured — you know exactly how to navigate treacherous situations.' },
    { number: 11, name: '泰', english: 'Peace', symbol: '䷊', upper: '000', lower: '111',
      judgment: '小往大来，吉亨。', judgmentEn: 'The small departs, the great approaches. Good fortune. Success.',
      image: '天地交泰，后以财成天地之道。', imageEn: 'Heaven and earth unite: the image of Peace. Thus the ruler orders the ways of heaven and earth.',
      keywords: ['Harmony', 'Prosperity', 'Flow', 'Balance'],
      personality: 'You create harmony wherever you go. Like heaven and earth in perfect communion, you bring together opposing forces into productive balance.' },
    { number: 12, name: '否', english: 'Standstill', symbol: '䷋', upper: '111', lower: '000',
      judgment: '否之匪人，不利君子贞。', judgmentEn: 'Standstill. The great departs, the small approaches. Not favorable for the perseverance of the great.',
      image: '天地不交，否。君子以俭德辟难。', imageEn: 'Heaven and earth do not unite: the image of Standstill. Thus the superior man falls back upon his inner worth.',
      keywords: ['Stagnation', 'Retreat', 'Inner Strength', 'Patience'],
      personality: 'When external circumstances stagnate, you retreat inward to cultivate your inner strength. You know that standstill is temporary and use it for deep preparation.' },
    { number: 13, name: '同人', english: 'Fellowship', symbol: '䷌', upper: '111', lower: '101',
      judgment: '同人于野，亨。利涉大川。', judgmentEn: 'Fellowship with men in the open. Success. It furthers one to cross the great water.',
      image: '天与火，同人。君子以类族辨物。', imageEn: 'Heaven together with fire: the image of Fellowship. Thus the superior man organizes the clans and makes distinctions between things.',
      keywords: ['Community', 'Shared Vision', 'Openness', 'Unity'],
      personality: 'You build fellowship through shared vision and open hearts. Your gift is bringing diverse people together under a common purpose.' },
    { number: 14, name: '大有', english: 'Great Possession', symbol: '䷍', upper: '101', lower: '111',
      judgment: '元亨。', judgmentEn: 'Supreme success.',
      image: '火在天上，大有。君子以遏恶扬善。', imageEn: 'Fire burns high in heaven: the image of Great Possession. Thus the superior man curbs evil and promotes good.',
      keywords: ['Abundance', 'Responsibility', 'Vision', 'Power'],
      personality: 'You carry the fire of great responsibility. With abundance comes the duty to use it wisely — to promote good and check evil in the world.' },
    { number: 15, name: '谦', english: 'Modesty', symbol: '䷎', upper: '000', lower: '001',
      judgment: '亨，君子有终。', judgmentEn: 'Success. The superior man carries things through.',
      image: '地中有山，谦。君子以裒多益寡。', imageEn: 'Within the earth, a mountain: the image of Modesty. Thus the superior man reduces what is excessive and increases what is insufficient.',
      keywords: ['Humility', 'Balance', 'True Strength', 'Wisdom'],
      personality: 'Your greatest power is your humility. Like a mountain hidden within the earth, your true strength is not displayed but deeply felt by all who know you.' },
    { number: 16, name: '豫', english: 'Enthusiasm', symbol: '䷏', upper: '000', lower: '100',
      judgment: '利建侯行师。', judgmentEn: 'It furthers one to install helpers and to set armies marching.',
      image: '雷出地奋，豫。先王以作乐崇德。', imageEn: 'Thunder comes resounding from the earth: the image of Enthusiasm. The ancient kings made music to honor virtue.',
      keywords: ['Enthusiasm', 'Inspiration', 'Movement', 'Joy'],
      personality: 'You inspire others through your infectious enthusiasm. Like thunder bursting from the earth, your energy awakens and mobilizes everyone around you.' },
    { number: 17, name: '随', english: 'Following', symbol: '䷐', upper: '110', lower: '100',
      judgment: '元亨利贞，无咎。', judgmentEn: 'Supreme success. Perseverance furthers. No blame.',
      image: '泽中有雷，随。君子以向晦入宴息。', imageEn: 'Thunder in the lake: the image of Following. Thus at nightfall the superior man goes home for rest.',
      keywords: ['Adaptability', 'Flow', 'Wisdom', 'Timing'],
      personality: 'You know when to lead and when to follow. Your wisdom lies in reading the moment and adapting your course like water finding its path.' },
    { number: 18, name: '蛊', english: 'Work on What Has Been Spoiled', symbol: '䷑', upper: '001', lower: '011',
      judgment: '元亨，利涉大川。先甲三日，后甲三日。', judgmentEn: 'Supreme success. It furthers one to cross the great water.',
      image: '山下有风，蛊。君子以振民育德。', imageEn: 'The wind blows low on the mountain: the image of Decay. Thus the superior man stirs up the people and strengthens their spirit.',
      keywords: ['Reform', 'Healing', 'Restoration', 'Duty'],
      personality: 'You are called to heal what has been damaged and restore what has been neglected. Your gift is seeing decay as an opportunity for renewal.' },
    { number: 19, name: '临', english: 'Approach', symbol: '䷒', upper: '000', lower: '110',
      judgment: '元亨利贞。至于八月有凶。', judgmentEn: 'Supreme success. Perseverance furthers. In the eighth month there will be misfortune.',
      image: '地上有泽，临。君子以教思无穷。', imageEn: 'The earth over the lake: the image of Approach. Thus the superior man is inexhaustible in his will to teach.',
      keywords: ['Approach', 'Generosity', 'Leadership', 'Expansion'],
      personality: 'You approach the world with generous leadership and inexhaustible patience. Your presence is like the earth embracing a lake — protective and nurturing.' },
    { number: 20, name: '观', english: 'Contemplation', symbol: '䷓', upper: '110', lower: '000',
      judgment: '盥而不荐，有孚颙若。', judgmentEn: 'The ablution has been made, but not yet the offering. Full of trust they look up to him.',
      image: '风行地上，观。先王以省方观民设教。', imageEn: 'The wind blows over the earth: the image of Contemplation. The ancient kings visited the regions and observed the people.',
      keywords: ['Observation', 'Insight', 'Perspective', 'Wisdom'],
      personality: 'You see what others miss. Your gift is deep observation — you contemplate before acting, and your insights carry the weight of careful thought.' },
    { number: 21, name: '噬嗑', english: 'Biting Through', symbol: '䷔', upper: '101', lower: '100',
      judgment: '亨。利用狱。', judgmentEn: 'Success. It is favorable to let justice be administered.',
      image: '雷电噬嗑。先王以明罚敕法。', imageEn: 'Thunder and lightning: the image of Biting Through. The ancient kings established clear penalties and enforced the laws.',
      keywords: ['Justice', 'Decisiveness', 'Clarity', 'Resolution'],
      personality: 'You cut through obstacles with decisive clarity. Like lightning and thunder together, your actions are swift, clear, and unmistakable.' },
    { number: 22, name: '贲', english: 'Grace', symbol: '䷕', upper: '001', lower: '101',
      judgment: '亨。小利有攸往。', judgmentEn: 'Success. In small matters it is favorable to undertake something.',
      image: '山下有火，贲。君子以明庶政。', imageEn: 'Fire at the foot of the mountain: the image of Grace. Thus the superior man brings clarity to daily affairs.',
      keywords: ['Beauty', 'Elegance', 'Refinement', 'Artistry'],
      personality: 'You bring beauty and elegance to everything you touch. Your gift is refining the ordinary into the extraordinary through attention to aesthetic detail.' },
    { number: 23, name: '剥', english: 'Splitting Apart', symbol: '䷖', upper: '001', lower: '000',
      judgment: '不利有攸往。', judgmentEn: 'It does not further one to go anywhere.',
      image: '山附于地，剥。上以厚下安宅。', imageEn: 'The mountain rests on the earth: the image of Splitting Apart. Thus those above ensure stability by enriching the foundation.',
      keywords: ['Letting Go', 'Foundation', 'Stripping', 'Essentials'],
      personality: 'You understand that sometimes things must fall apart to reveal what is essential. Your wisdom is knowing when to let go and focus on the foundation.' },
    { number: 24, name: '复', english: 'Return', symbol: '䷗', upper: '000', lower: '100',
      judgment: '亨。出入无疾。', judgmentEn: 'Success. Going out and coming in without error.',
      image: '雷在地中，复。先王以至日闭关。', imageEn: 'Thunder within the earth: the image of Return. At the time of solstice the kings closed the passes.',
      keywords: ['Renewal', 'Cycles', 'Return', 'Hope'],
      personality: 'Like the first stirring of spring beneath frozen earth, you carry the energy of renewal. You understand that every ending is a new beginning.' },
    { number: 25, name: '无妄', english: 'Innocence', symbol: '䷘', upper: '111', lower: '100',
      judgment: '元亨利贞。', judgmentEn: 'Supreme success. Perseverance furthers.',
      image: '天下雷行，物与无妄。', imageEn: 'Thunder rolls beneath heaven: the image of Innocence. All things proceed in accordance with their nature.',
      keywords: ['Authenticity', 'Naturalness', 'Spontaneity', 'Truth'],
      personality: 'You act from a place of pure authenticity. Your strength is in your innocence — not naivety, but the courage to be genuinely yourself.' },
    { number: 26, name: '大畜', english: 'The Taming Power of the Great', symbol: '䷙', upper: '001', lower: '111',
      judgment: '利贞。不家食吉。利涉大川。', judgmentEn: 'Perseverance furthers. It is favorable to not eat at home. It furthers one to cross the great water.',
      image: '天在山中，大畜。君子以多识前言往行。', imageEn: 'Heaven within the mountain: Great Taming. Thus the superior man studies the words and deeds of the past.',
      keywords: ['Accumulation', 'Knowledge', 'Restraint', 'Power'],
      personality: 'You accumulate great power through patience and learning. Like heaven contained within a mountain, your potential is vast and carefully held.' },
    { number: 27, name: '颐', english: 'Nourishment', symbol: '䷚', upper: '001', lower: '100',
      judgment: '贞吉。观颐，自求口实。', judgmentEn: 'Perseverance brings good fortune. Observe nourishment and seek nourishment for yourself.',
      image: '山下有雷，颐。君子以慎言语。', imageEn: 'Thunder at the foot of the mountain: Nourishment. Thus the superior man is careful with his words.',
      keywords: ['Nourishment', 'Care', 'Speech', 'Sustenance'],
      personality: 'You understand that what nourishes the body and soul must be chosen carefully. Your wisdom extends to what you consume — food, words, ideas.' },
    { number: 28, name: '大过', english: 'Preponderance of the Great', symbol: '䷛', upper: '110', lower: '011',
      judgment: '栋桡。利有攸往，亨。', judgmentEn: 'The ridgepole sags to the breaking point. It furthers one to have somewhere to go. Success.',
      image: '泽灭木，大过。君子以独立不惧。', imageEn: 'The lake rises over the trees: Preponderance of the Great. Thus the superior man stands alone without fear.',
      keywords: ['Excess', 'Independence', 'Courage', 'Decisiveness'],
      personality: 'You stand at a point of great tension — when the weight of the world tests your spine. Your courage is in standing alone when necessary.' },
    { number: 29, name: '坎', english: 'The Abysmal', symbol: '䷜', upper: '010', lower: '010',
      judgment: '习坎，有孚，维心亨。', judgmentEn: 'The Abysmal repeated. If you are sincere, you have success in your heart.',
      image: '水洊至，习坎。君子以常德行。', imageEn: 'Water flows on uninterruptedly: the Abysmal. Thus the superior man walks in lasting virtue.',
      keywords: ['Danger', 'Resilience', 'Flow', 'Inner Truth'],
      personality: 'Like water that flows through the deepest valleys, you possess incredible resilience. Your strength is in moving through danger without losing your essential nature.' },
    { number: 30, name: '离', english: 'The Clinging', symbol: '䷝', upper: '101', lower: '101',
      judgment: '利贞，亨。畜牝牛，吉。', judgmentEn: 'Perseverance furthers. Success. Cultivating a cow brings good fortune.',
      image: '明两作，离。大人以继明照于四方。', imageEn: 'Fire keeps rising: Clinging. Thus the brilliant man continues his work and illuminates the four quarters.',
      keywords: ['Clarity', 'Awareness', 'Illumination', 'Dependence'],
      personality: 'You bring clarity and illumination wherever you go. Like fire that clings to its fuel, you draw your power from the things and people you are attached to.' },
    { number: 31, name: '咸', english: 'Influence', symbol: '䷞', upper: '110', lower: '001',
      judgment: '亨，利贞。取女吉。', judgmentEn: 'Success. Perseverance furthers. To take a maiden brings good fortune.',
      image: '山上有泽，咸。君子以虚受人。', imageEn: 'A lake on the mountain: Influence. Thus the superior man encourages people to approach him by being receptive.',
      keywords: ['Attraction', 'Sensitivity', 'Connection', 'Receptivity'],
      personality: 'You influence others through genuine receptivity and sensitivity. Like a lake atop a mountain, you attract through openness and emotional depth.' },
    { number: 32, name: '恒', english: 'Duration', symbol: '䷟', upper: '000', lower: '100',
      judgment: '亨，无咎。利贞。', judgmentEn: 'Success. No blame. Perseverance furthers.',
      image: '雷风恒。君子以立不易方。', imageEn: 'Thunder and wind: Duration. Thus the superior man stands firm and does not change his direction.',
      keywords: ['Persistence', 'Consistency', 'Endurance', 'Faithfulness'],
      personality: 'You embody the power of duration — not stubbornness, but the deep consistency of thunder and wind that shapes mountains over time.' },
    { number: 33, name: '遁', english: 'Retreat', symbol: '䷠', upper: '111', lower: '001',
      judgment: '亨。小利贞。', judgmentEn: 'Success. In small matters perseverance furthers.',
      image: '天下有山，遁。君子以远小人。', imageEn: 'Mountain under heaven: Retreat. Thus the superior man keeps the inferior at a distance.',
      keywords: ['Strategic Retreat', 'Wisdom', 'Self-Preservation', 'Timing'],
      personality: 'You know that strategic retreat is not weakness but wisdom. Like a mountain that stands apart from heaven, you maintain your integrity by knowing when to step back.' },
    { number: 34, name: '大壮', english: 'The Power of the Great', symbol: '䷡', upper: '111', lower: '100',
      judgment: '利贞。', judgmentEn: 'Perseverance furthers.',
      image: '雷在天上，大壮。君子以非礼弗履。', imageEn: 'Thunder rising to heaven: Great Power. Thus the superior man does not tread upon paths that do not accord with the order.',
      keywords: ['Power', 'Strength', 'Righteousness', 'Restraint'],
      personality: 'You possess great power, but your wisdom is in using it righteously. Like thunder in the sky, your strength is awe-inspiring yet guided by propriety.' },
    { number: 35, name: '晋', english: 'Progress', symbol: '䷢', upper: '101', lower: '000',
      judgment: '康侯用锡马蕃庶，昼日三接。', judgmentEn: 'Progress. The prince is honored with horses. He is received in audience three times in a single day.',
      image: '明出地上，晋。君子以自昭明德。', imageEn: 'The sun rises over the earth: Progress. Thus the superior man brightens his virtue.',
      keywords: ['Progress', 'Recognition', 'Advancement', 'Visibility'],
      personality: 'You are in a time of rapid advancement and recognition. Like the sun rising over the earth, your efforts become visible and rewarded.' },
    { number: 36, name: '明夷', english: 'Darkening of the Light', symbol: '䷣', upper: '000', lower: '101',
      judgment: '利艰贞。', judgmentEn: 'It is favorable to maintain perseverance through difficulty.',
      image: '明入地中，明夷。君子以莅众。', imageEn: 'The light has sunk into the earth: Darkening of the Light. Thus the superior man governs the multitude with wisdom.',
      keywords: ['Hidden Light', 'Perseverance', 'Inner Strength', 'Sacrifice'],
      personality: 'Your light shines brightest in darkness. When the world dims, you preserve your inner radiance and guide others through the shadows.' },
    { number: 37, name: '家人', english: 'The Family', symbol: '䷤', upper: '110', lower: '101',
      judgment: '利女贞。', judgmentEn: 'The perseverance of the woman furthers.',
      image: '风自火出，家人。君子以言有物。', imageEn: 'Wind comes forth from fire: The Family. Thus the superior man has substance in his words.',
      keywords: ['Family', 'Order', 'Nurture', 'Foundation'],
      personality: 'You create order and warmth in your inner circle. Like fire fed by wind, your family and close relationships are where your true power radiates.' },
    { number: 38, name: '睽', english: 'Opposition', symbol: '䷥', upper: '101', lower: '110',
      judgment: '小事吉。', judgmentEn: 'In small matters good fortune.',
      image: '上火下泽，睽。君子以同而异。', imageEn: 'Fire above, the lake below: Opposition. Thus the superior man seeks unity in diversity.',
      keywords: ['Diversity', 'Tension', 'Creativity', 'Perspective'],
      personality: 'You thrive in the creative tension between opposites. Your gift is seeing how different perspectives can coexist and even enrich each other.' },
    { number: 39, name: '蹇', english: 'Obstruction', symbol: '䷦', upper: '010', lower: '001',
      judgment: '利西南。不利东北。', judgmentEn: 'It furthers one to go southwest. It does not further one to go northeast.',
      image: '山上有水，蹇。君子以反身修德。', imageEn: 'Water on the mountain: Obstruction. Thus the superior man turns inward to cultivate his virtue.',
      keywords: ['Obstacles', 'Self-Reflection', 'Perseverance', 'Inner Work'],
      personality: 'When obstacles arise, you turn inward rather than fighting outward. Your strength is in self-cultivation during difficult times.' },
    { number: 40, name: '解', english: 'Deliverance', symbol: '䷧', upper: '000', lower: '010',
      judgment: '利西南。无所往，其来复吉。', judgmentEn: 'It furthers one to go southwest. If there is no longer anything to do, return brings good fortune.',
      image: '雷雨作，解。君子以赦过宥罪。', imageEn: 'Thunder and rain set in: Deliverance. Thus the superior man pardons mistakes and forgives misdeeds.',
      keywords: ['Liberation', 'Forgiveness', 'Release', 'Renewal'],
      personality: 'You bring liberation and forgiveness. Like the first thunderstorm after drought, your presence releases tension and brings renewal.' },
    { number: 41, name: '损', english: 'Decrease', symbol: '䷨', upper: '001', lower: '110',
      judgment: '有孚，元吉。', judgmentEn: 'Sincerity brings supreme good fortune.',
      image: '山下有泽，损。君子以惩忿窒欲。', imageEn: 'A lake at the foot of the mountain: Decrease. Thus the superior man controls his anger and restrains his desires.',
      keywords: ['Simplification', 'Sacrifice', 'Essence', 'Restraint'],
      personality: 'You understand that less is more. By stripping away the unnecessary, you reveal the essential truth and find freedom in simplicity.' },
    { number: 42, name: '益', english: 'Increase', symbol: '䷩', upper: '110', lower: '100',
      judgment: '利有攸往。利涉大川。', judgmentEn: 'It furthers one to undertake something. It furthers one to cross the great water.',
      image: '风雷，益。君子以见善则迁。', imageEn: 'Wind and thunder: Increase. Thus when the superior man sees good, he follows it.',
      keywords: ['Growth', 'Expansion', 'Opportunity', 'Generosity'],
      personality: 'You are in a time of powerful growth. Like wind and thunder amplifying each other, your actions create momentum that benefits everyone.' },
    { number: 43, name: '夬', english: 'Breakthrough', symbol: '䷪', upper: '111', lower: '110',
      judgment: '扬于王庭。孚号有厉。', judgmentEn: 'Breakthrough is proclaimed in the royal court. With truthfulness there is cause for anxiety.',
      image: '泽上于天，夬。君子以施禄及下。', imageEn: 'The lake has risen to heaven: Breakthrough. Thus the superior man distributes fortune below.',
      keywords: ['Decisiveness', 'Breakthrough', 'Courage', 'Resolution'],
      personality: 'You are at the point of decisive breakthrough. Like a lake overflowing into heaven, your accumulated power demands bold, courageous action.' },
    { number: 44, name: '姤', english: 'Coming to Meet', symbol: '䷫', upper: '111', lower: '011',
      judgment: '女壮，勿用取女。', judgmentEn: 'The maiden is powerful. It is not good to marry such a maiden.',
      image: '天下有风，姤。后以施命诰四方。', imageEn: 'Under heaven, wind: Coming to Meet. Thus the sovereign publishes his commands to the four quarters.',
      keywords: ['Encounter', 'Temptation', 'Awareness', 'Caution'],
      personality: 'You must be alert to unexpected encounters. Not every meeting is beneficial — your wisdom is in discerning which connections to nurture and which to avoid.' },
    { number: 45, name: '萃', english: 'Gathering Together', symbol: '䷬', upper: '110', lower: '000',
      judgment: '亨。王假有庙。', judgmentEn: 'Success. The king approaches his temple.',
      image: '泽上于地，萃。君子以除戎器。', imageEn: 'Over the earth, the lake: Gathering Together. Thus the superior man renews his weapons.',
      keywords: ['Community', 'Unity', 'Gathering', 'Preparation'],
      personality: 'You bring people together for a common purpose. Your gift is creating spaces where others feel they belong and can contribute.' },
    { number: 46, name: '升', english: 'Pushing Upward', symbol: '䷭', upper: '000', lower: '011',
      judgment: '南征吉。', judgmentEn: 'Progress to the south brings good fortune.',
      image: '地中生木，升。君子以顺德。', imageEn: 'Wood growing within the earth: Pushing Upward. Thus the superior man accumulates small things to achieve something high.',
      keywords: ['Growth', 'Advancement', 'Patience', 'Steady Progress'],
      personality: 'You grow steadily upward like a tree from the earth. Your progress may seem slow, but it is unstoppable because it is rooted in virtue.' },
    { number: 47, name: '困', english: 'Oppression', symbol: '䷮', upper: '110', lower: '010',
      judgment: '亨。贞大人吉。', judgmentEn: 'Success. The perseverance of the great person brings good fortune.',
      image: '泽无水，困。君子以致命遂志。', imageEn: 'The lake has no water: Oppression. Thus the superior man stakes his life on following his will.',
      keywords: ['Adversity', 'Resilience', 'Will', 'Inner Strength'],
      personality: 'You find strength in the deepest adversity. When the lake runs dry, you discover that your true power was never in external resources but in your unbreakable will.' },
    { number: 48, name: '井', english: 'The Well', symbol: '䷯', upper: '010', lower: '011',
      judgment: '改邑不改井。', judgmentEn: 'The town may be changed, but the well cannot be changed.',
      image: '木上有水，井。君子以劳民劝相。', imageEn: 'Water over wood: The Well. Thus the superior man encourages the people and exhorts them to help one another.',
      keywords: ['Nourishment', 'Constancy', 'Community', 'Foundation'],
      personality: 'You are the well that never runs dry — a constant source of nourishment and wisdom for your community. Your value is timeless and unchanging.' },
    { number: 49, name: '革', english: 'Revolution', symbol: '䷰', upper: '110', lower: '101',
      judgment: '己日乃孚。元亨利贞。', judgmentEn: 'On the day of revolution, sincerity brings supreme success.',
      image: '泽中有火，革。君子以治历明时。', imageEn: 'Fire within the lake: Revolution. Thus the superior man sets the calendar and makes the seasons clear.',
      keywords: ['Change', 'Transformation', 'Innovation', 'Timing'],
      personality: 'You are a natural revolutionary who understands that true change must come at the right time. Your gift is transforming what no longer serves.' },
    { number: 50, name: '鼎', english: 'The Cauldron', symbol: '䷱', upper: '101', lower: '011',
      judgment: '元吉，亨。', judgmentEn: 'Supreme good fortune. Success.',
      image: '木上有火，鼎。君子以正位凝命。', imageEn: 'Fire over wood: The Cauldron. Thus the superior man consolidates his fate by making his position correct.',
      keywords: ['Transformation', 'Nourishment', 'Culture', 'Legacy'],
      personality: 'You transform raw experience into wisdom and nourishment. Like the ancient cauldron, you are a vessel of civilization and cultural refinement.' },
    { number: 51, name: '震', english: 'The Arousing', symbol: '䷲', upper: '100', lower: '100',
      judgment: '亨。震来虩虩，笑言哑哑。', judgmentEn: 'Success. Thunder comes with terror and laughter.',
      image: '洊雷，震。君子以恐惧修省。', imageEn: 'Thunder repeated: Arousing. Thus the superior man in fear and trembling sets his life in order.',
      keywords: ['Awakening', 'Shock', 'Reverence', 'Vitality'],
      personality: 'You carry the power of thunder — your presence awakens and energizes. You understand that fear, when properly channeled, becomes the fuel for growth.' },
    { number: 52, name: '艮', english: 'Keeping Still', symbol: '䷳', upper: '001', lower: '001',
      judgment: '艮其背，不获其身。', judgmentEn: 'Keeping his back still, so that he no longer feels his body.',
      image: '兼山，艮。君子以思不出其位。', imageEn: 'Mountains standing together: Stillness. Thus the superior man does not go beyond what is right.',
      keywords: ['Stillness', 'Meditation', 'Boundaries', 'Inner Peace'],
      personality: 'You possess the profound stillness of a mountain. In meditation and reflection, you find clarity that others miss in their constant motion.' },
    { number: 53, name: '渐', english: 'Development', symbol: '䷴', upper: '110', lower: '001',
      judgment: '女归吉。利贞。', judgmentEn: 'Development. The maiden is given in marriage. Good fortune.',
      image: '山上有木，渐。君子以居贤德善俗。', imageEn: 'Trees on the mountain: Development. Thus the superior man abides in dignity and improves customs.',
      keywords: ['Gradual Progress', 'Patience', 'Order', 'Natural Growth'],
      personality: 'You understand that lasting development happens gradually, like trees growing on a mountain. Your patience creates results that endure.' },
    { number: 54, name: '归妹', english: 'The Marrying Maiden', symbol: '䷵', upper: '000', lower: '100',
      judgment: '征凶。无攸利。', judgmentEn: 'Undertakings bring misfortune. Nothing that would further.',
      image: '泽上有雷，归妹。君子以永终知敝。', imageEn: 'Thunder over the lake: The Marrying Maiden. Thus the superior man understands the transitory nature of things.',
      keywords: ['Transitions', 'Commitment', 'Awareness', 'Impermanence'],
      personality: 'You navigate life\'s transitions with awareness of impermanence. Your wisdom is in understanding that every role is temporary.' },
    { number: 55, name: '丰', english: 'Abundance', symbol: '䷶', upper: '100', lower: '101',
      judgment: '亨。王假之。', judgmentEn: 'Success. The king attains abundance.',
      image: '雷电皆至，丰。君子以折狱致刑。', imageEn: 'Thunder and lightning come together: Abundance. Thus the superior man decides lawsuits and inflicts penalties.',
      keywords: ['Peak', 'Abundance', 'Clarity', 'Responsibility'],
      personality: 'You are at the peak of your power — like lightning and thunder illuminating the sky. At this height, your responsibility is to use your abundance wisely.' },
    { number: 56, name: '旅', english: 'The Wanderer', symbol: '䷷', upper: '101', lower: '001',
      judgment: '小亨。旅贞吉。', judgmentEn: 'Small success. The perseverance of the wanderer brings good fortune.',
      image: '山上有火，旅。君子以明慎用刑。', imageEn: 'Fire on the mountain: The Wanderer. Thus the superior man is clear-minded and cautious in imposing penalties.',
      keywords: ['Freedom', 'Adaptability', 'Observation', 'Independence'],
      personality: 'You are a soul in motion — seeing the world with fresh eyes, unattached to any single place. Your freedom is your greatest gift.' },
    { number: 57, name: '巽', english: 'The Gentle', symbol: '䷸', upper: '110', lower: '011',
      judgment: '小亨。利有攸往。', judgmentEn: 'Success through what is small. It furthers one to have somewhere to go.',
      image: '随风，巽。君子以申命行事。', imageEn: 'Wind following wind: The Gentle. Thus the superior man repeats his command and carries it through.',
      keywords: ['Gentleness', 'Penetration', 'Persistence', 'Flexibility'],
      personality: 'You penetrate everything with gentle persistence. Like wind that shapes stone over centuries, your influence is soft but ultimately irresistible.' },
    { number: 58, name: '兑', english: 'The Joyous', symbol: '䷹', upper: '110', lower: '110',
      judgment: '亨。利贞。', judgmentEn: 'Success. Perseverance furthers.',
      image: '丽泽，兑。君子以朋友讲习。', imageEn: 'Lake connects with lake: Joy. Thus the superior man discusses with friends and practices together.',
      keywords: ['Joy', 'Communication', 'Community', 'Inspiration'],
      personality: 'You radiate joy that inspires and connects. Like two lakes reflecting each other, your happiness multiplies when shared with others.' },
    { number: 59, name: '涣', english: 'Dispersion', symbol: '䷺', upper: '110', lower: '010',
      judgment: '亨。王假有庙。', judgmentEn: 'Success. The king approaches his temple.',
      image: '风行水上，涣。先王以享于帝立庙。', imageEn: 'Wind blowing over water: Dispersion. Thus the ancient kings made offerings to the Lord and established temples.',
      keywords: ['Dissolution', 'Release', 'Unity', 'Spiritual Connection'],
      personality: 'You dissolve barriers between people and ideas. Like wind over water, you create movement where there was stagnation and connection where there was isolation.' },
    { number: 60, name: '节', english: 'Limitation', symbol: '䷻', upper: '010', lower: '110',
      judgment: '亨。苦节不可贞。', judgmentEn: 'Success. Bitter limitation cannot be persevered in.',
      image: '泽上有水，节。君子以制数度。', imageEn: 'Water over the lake: Limitation. Thus the superior man creates measures and judgments.',
      keywords: ['Boundaries', 'Structure', 'Discipline', 'Balance'],
      personality: 'You understand that healthy boundaries create freedom. Your wisdom is in knowing which limitations serve growth and which restrict it.' },
    { number: 61, name: '中孚', english: 'Inner Truth', symbol: '䷼', upper: '110', lower: '100',
      judgment: '豚鱼吉。利涉大川。', judgmentEn: 'Success. Even pigs and fishes are affected. It furthers one to cross the great water.',
      image: '泽上有风，中孚。君子以议狱缓死。', imageEn: 'Wind over the lake: Inner Truth. Thus the superior man discusses criminal cases to delay executions.',
      keywords: ['Truth', 'Sincerity', 'Influence', 'Compassion'],
      personality: 'Your inner truth is so powerful it moves even the simplest creatures. You influence not through force but through the sheer authenticity of your being.' },
    { number: 62, name: '小过', english: 'Preponderance of the Small', symbol: '䷽', upper: '000', lower: '100',
      judgment: '亨。利贞。', judgmentEn: 'Success. Perseverance furthers.',
      image: '山上有雷，小过。君子以行过乎恭。', imageEn: 'Thunder on the mountain: Small Exceeding. Thus the superior man practices excessive humility.',
      keywords: ['Humility', 'Attention to Detail', 'Caution', 'Modesty'],
      personality: 'You excel in the small things that others overlook. Your attention to detail and humility in action create results that exceed expectations.' },
    { number: 63, name: '既济', english: 'After Completion', symbol: '䷾', upper: '010', lower: '101',
      judgment: '亨小利贞。初吉终乱。', judgmentEn: 'Success in small matters. Perseverance furthers. At the beginning good fortune, at the end disorder.',
      image: '水在火上，既济。君子以思患而豫防之。', imageEn: 'Water over fire: After Completion. Thus the superior man thinks of misfortune and guards against it in advance.',
      keywords: ['Completion', 'Vigilance', 'Transition', 'Prevention'],
      personality: 'You understand that completion is not the end but a moment of transition. Your vigilance prevents the disorder that often follows apparent success.' },
    { number: 64, name: '未济', english: 'Before Completion', symbol: '䷿', upper: '101', lower: '010',
      judgment: '亨。小狐汔济。', judgmentEn: 'Success. The little fox has nearly crossed the stream.',
      image: '火在水上，未济。君子以慎辨物居方。', imageEn: 'Fire over water: Before Completion. Thus the superior man carefully discriminates things and settles them in their places.',
      keywords: ['Potential', 'Transition', 'Carefulness', 'New Beginnings'],
      personality: 'You stand at the threshold of completion — so close, yet the final step requires the most care. Your potential is infinite if you remain vigilant to the end.' },
  ],

  /**
   * 通过出生日期生成卦象（简化算法）
   */
  getHexagramByBirth(birthDate, birthTime) {
    const d = new Date(birthDate + 'T' + (birthTime || '12:00'));
    const seed = d.getTime();
    const index = Math.abs(seed) % 64;
    return this.HEXAGRAMS[index];
  },

  /**
   * 随机占卜（模拟投币法）
   */
  castHexagram() {
    // 模拟三枚铜钱投6次
    const lines = [];
    for (let i = 0; i < 6; i++) {
      let sum = 0;
      for (let j = 0; j < 3; j++) {
        sum += Math.random() < 0.5 ? 2 : 3; // 正面=3，反面=2
      }
      lines.push(sum);
    }
    // 6=老阴(变), 7=少阳, 8=少阴, 9=老阳(变)
    const binary = lines.map(l => (l === 6 || l === 7) ? '1' : '0');
    const upperTrigram = binary.slice(0, 3).join('');
    const lowerTrigram = binary.slice(3, 6).join('');

    const hex = this.HEXAGRAMS.find(h => h.upper === upperTrigram && h.lower === lowerTrigram);
    return hex || this.HEXAGRAMS[0];
  },

  /**
   * 获取卦的完整信息
   */
  getHexagramInfo(hexagram) {
    const upperTri = this.TRIGRAMS[hexagram.upper];
    const lowerTri = this.TRIGRAMS[hexagram.lower];
    return {
      ...hexagram,
      upperTrigram: upperTri,
      lowerTrigram: lowerTri,
    };
  },
};
